### PR TITLE
libcgroup.map: include cgroup_get_cgroup_name

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
Using cgroup_get_cgroup_name() API, fails with:
```
gcc -o cgrp_get_cgrp_name cgrp_get_cgrp_name.c -lcgroup /usr/bin/ld: /tmp/ccIyBv5c.o: in function `main':
cgrp_get_cgrp_name.c:(.text+0xaa): undefined reference to `cgroup_get_cgroup_name'
collect2: error: ld returned 1 exit status
```
The API was introduced by commit ca32d88ef56b1 ("wrappers: Add a cgroup_get_cgroup_name API") but missed adding it to libcgroup.map file, causing the linkage issue. Fix the issue by adding the API at the libcgroup.map under version it was introduced.

### CODE REVIEW

**Review by drakenclimber — APPROVED** [review]
LGTM

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by drakenclimber** [comment]
Pushed to main in commit 861a9369d234.  Thanks, @kamalesh-babulal and @Noisytoot

**Comment by drakenclimber** [comment]
I also pushed it to the release-3.1 branch as well in commit d6eab65904b0
